inherit_gem:
  rubocop-florence: config/.florence.rubocop.yml
inherit_mode:
  merge:
    - Exclude
Naming/FileName:
  Exclude:
    - lib/rubocop-florence.rb
Rails:
  Enabled: false
RSpec:
  Language:
    Expectations:
      - expect_no_offenses
      - expect_offense
RSpec/ExampleLength:
  CountAsOne:
    - heredoc
