inherit_mode:
  merge:
    - Exclude
    - Environments

AllCops:
  NewCops: enable

Florence/UuidPrimaryKey:
  Description: "Database tables should use uuid primary keys."
  Enabled: false
  VersionAdded: "0.12.0"
Florence/ServiceSingleEntryPoint:
  Description: "Service objects should only have one entry point."
  Enabled: false
  VersionAdded: "0.3.0"
  Include: ["app/**/services/**/*.rb"]

Layout/FirstArgumentIndentation:
  EnforcedStyle: consistent
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
Layout/FirstArrayElementLineBreak:
  Enabled: true
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Layout/FirstHashElementLineBreak:
  Enabled: true
Layout/FirstMethodArgumentLineBreak:
  Enabled: true
Layout/FirstMethodParameterLineBreak:
  Enabled: true
Layout/MultilineMethodArgumentLineBreaks:
  Enabled: true
Layout/MultilineMethodParameterLineBreaks:
  Enabled: true

Lint/MissingSuper:
  Enabled: false

Metrics/BlockLength:
  Exclude: [./config/routes.rb]

Metrics/ParameterLists:
  CountKeywordArgs: false

Rails/UnknownEnv:
  Environments: [staging]
Rails/WhereRange:
  Enabled: false

RSpec/ExpectInHook:
  Enabled: false
RSpec/StubbedMock:
  Enabled: false

Style/DisableCopsWithinSourceCodeDirective:
  Enabled: true
Style/Documentation:
  Enabled: false
Style/HashSyntax:
  EnforcedShorthandSyntax: never
