inherit_mode:
  merge:
    - Exclude
    - Environments

AllCops:
  NewCops: enable
Lint/MissingSuper:
  Enabled: false
Metrics/BlockLength:
  Exclude: [./config/routes.rb]
Rails/UnknownEnv:
  Environments: [staging]
RSpec/ExpectInHook:
  Enabled: false
RSpec/StubbedMock:
  Enabled: false
Style/Documentation:
  Enabled: false
